'use client';
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import InfoViewContextProvider from "@/@devdocs/context/AppContextProvider/InfoViewContextProvider";
import AppAuthProvider from "@/@devdocs/core/AppAuthProvider";
import AuthRoutes from "@/@devdocs/components/AuthRoutes";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
type Props = {
  children: React.ReactNode;
};
export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <InfoViewContextProvider>
          <AppAuthProvider>
            <AuthRoutes>
              {children}
            </AuthRoutes>
          </AppAuthProvider>
        </InfoViewContextProvider>
      </body>
    </html>
  );
}
